/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LuckyTravel;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class ChooseCharacter extends javax.swing.JFrame {

   
    int woman_number,man_number;
    int male,female;
    static String[] photo={"",""};
    static String[] color_type={"",""};
    int index=0;
    int counter=0;
    public ChooseCharacter() {
        initComponents();
        rad_1.setVisible(false);
        rad_2.setVisible(false);
        btn_next.setVisible(false);
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_photo1 = new javax.swing.JLabel();
        btn_choose = new javax.swing.JButton();
        lbl_exp = new javax.swing.JLabel();
        rad_1 = new javax.swing.JRadioButton();
        lbl_photo2 = new javax.swing.JLabel();
        rad_2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        btn_male = new javax.swing.JButton();
        btn_female = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_choose.setText("Choose");
        btn_choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chooseActionPerformed(evt);
            }
        });

        lbl_exp.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lbl_exp.setText("Choose The First Character");

        rad_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_1ActionPerformed(evt);
            }
        });

        rad_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("  Gender");

        btn_male.setText("Male");
        btn_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_maleActionPerformed(evt);
            }
        });

        btn_female.setText("Female");
        btn_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_femaleActionPerformed(evt);
            }
        });

        btn_next.setText("Next  >");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_female, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_male, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(rad_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_photo1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(rad_2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_photo2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_next)
                            .addComponent(btn_choose))
                        .addGap(25, 25, 25))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_exp, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_exp, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btn_next)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_choose))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rad_2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(rad_1))
                                .addGap(18, 18, 18)
                                .addComponent(btn_male)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_female))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lbl_photo1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_photo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(128, 128, 128)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_femaleActionPerformed
        female=1;male=0;
        rad_1.setVisible(true);
        rad_2.setVisible(true);
        try{
      
          lbl_photo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/woman_1.png")));
          lbl_photo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/woman_2.png")));
          
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,e.toString());
       }
    }//GEN-LAST:event_btn_femaleActionPerformed

    private void btn_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_maleActionPerformed
    male=1;female=0;
    rad_1.setVisible(true);
    rad_2.setVisible(true);
        try{
      
          lbl_photo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man_1.png")));
          lbl_photo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man_2.png")));
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,e.toString());
       }
        
    }//GEN-LAST:event_btn_maleActionPerformed

    private void rad_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_1ActionPerformed
      rad_2.setSelected(false);
        if (male==1) {
            man_number=1;
        }
        else{
            woman_number=1;
        }
      
    }//GEN-LAST:event_rad_1ActionPerformed

    private void rad_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_2ActionPerformed
      rad_1.setSelected(false);
        if (male==1) {
            man_number=2;
        }
        else{
            woman_number=2;
        }
    }//GEN-LAST:event_rad_2ActionPerformed

    private void btn_chooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chooseActionPerformed
     
     
             
        try{
             if (index>=0 && index<2) {
            if (male==1 && man_number==1 ) {
        photo[index]="/images/man_1.png";
        index++;
        }
        else if(male==1 && man_number==2){
        photo[index]="/images/man_2.png"; 
        index++;
        }
        else if(female==1 && woman_number==1){
        photo[index]="/images/woman_1.png";
        index++;
        }
        else {
        photo[index]="/images/woman_2.png";
        index++;
        }
        if (index<3) {
        JOptionPane.showMessageDialog(null,"Character "+(counter+1)+"  Choosed");
           counter++;
        }
        if (index==1) {
        lbl_exp.setText("Choose The Second Character");
        }
        if (photo[0].length()>1 && photo[1].length()>1) {
        lbl_exp.setText("All Characters are Choosed ");
        btn_choose.setVisible(false);
        btn_next.setVisible(true);
             }   
        }
         
        else{
        JOptionPane.showMessageDialog(null,"Characters are choosed already");   
        }
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,e.toString());     
        }
       
        
        
        
       
      
       
    }//GEN-LAST:event_btn_chooseActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamePage().setVisible(true);
            }
        });
          this.dispose();
    }//GEN-LAST:event_btn_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseCharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseCharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseCharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseCharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseCharacter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_choose;
    private javax.swing.JButton btn_female;
    private javax.swing.JButton btn_male;
    private javax.swing.JButton btn_next;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_exp;
    private javax.swing.JLabel lbl_photo1;
    private javax.swing.JLabel lbl_photo2;
    private javax.swing.JRadioButton rad_1;
    private javax.swing.JRadioButton rad_2;
    // End of variables declaration//GEN-END:variables
}
